In [240]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import math
from sklearn.preprocessing import LabelEncoder
from collections import Counter

In [241]:
df = pd.read_csv('zomato.csv')

In [242]:
print(df.shape)
print(df.info())

(51717, 17)
<class 'pandas.DataFrame'>
RangeIndex: 51717 entries, 0 to 51716
Data columns (total 17 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   url                          51717 non-null  str
 1   address                      51717 non-null  str
 2   name                         51717 non-null  str
 3   online_order                 51717 non-null  str
 4   book_table                   51717 non-null  str
 5   rate                         43942 non-null  str
 6   votes                        51717 non-null  int64
 7   phone                        50509 non-null  str
 8   location                     51696 non-null  str
 9   rest_type                    51490 non-null  str
 10  dish_liked                   23639 non-null  str
 11  cuisines                     51672 non-null  str
 12  approx_cost(for two people)  51371 non-null  str
 13  reviews_list                 51717 non-null  str
 14  menu_item                    51717 non-null  str
 15  listed_in(type)              51717 non-null  str
 16  listed_in(city)              51717 non-null  str
dtypes: int64(1), str(16)
memory usage: 6.7 MB
None

In [243]:
df.head()

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari
2,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari
3,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",Addhuri Udupi Bhojana,No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari
4,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",Grand Village,No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari

In [244]:
null_values =df.isnull().mean().mul(100)
# null_values.sort()
print(null_values.sort_values())

url                             0.000000
address                         0.000000
name                            0.000000
online_order                    0.000000
book_table                      0.000000
votes                           0.000000
listed_in(type)                 0.000000
menu_item                       0.000000
reviews_list                    0.000000
listed_in(city)                 0.000000
location                        0.040606
cuisines                        0.087012
rest_type                       0.438927
approx_cost(for two people)     0.669026
phone                           2.335789
rate                           15.033741
dish_liked                     54.291626
dtype: float64

In [245]:
df[df.duplicated()].shape[0]

0

In [246]:
df.drop(['url','address','dish_liked','phone','menu_item','reviews_list','listed_in(city)'],axis =1 ,inplace = True)

In [247]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 51717 entries, 0 to 51716
Data columns (total 10 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   name                         51717 non-null  str
 1   online_order                 51717 non-null  str
 2   book_table                   51717 non-null  str
 3   rate                         43942 non-null  str
 4   votes                        51717 non-null  int64
 5   location                     51696 non-null  str
 6   rest_type                    51490 non-null  str
 7   cuisines                     51672 non-null  str
 8   approx_cost(for two people)  51371 non-null  str
 9   listed_in(type)              51717 non-null  str
dtypes: int64(1), str(9)
memory usage: 3.9 MB

In [248]:
le_onlineoreder = LabelEncoder()
le_booktable = LabelEncoder()
df["online_orderN"] = le_onlineoreder.fit_transform(df['online_order'])
df["book_tableN"] = le_booktable.fit_transform(df['book_table'])
df.drop(columns=['online_order'],inplace=True)
df.drop(columns=['book_table'],inplace=True)
df.head(100)

,name,rate,votes,location,rest_type,cuisines,approx_cost(for two people),listed_in(type),online_orderN,book_tableN
0,Jalsa,4.1/5,775,Banashankari,Casual Dining,"North Indian, Mughlai, Chinese",800,Buffet,1,1
1,Spice Elephant,4.1/5,787,Banashankari,Casual Dining,"Chinese, North Indian, Thai",800,Buffet,1,0
2,San Churro Cafe,3.8/5,918,Banashankari,"Cafe, Casual Dining","Cafe, Mexican, Italian",800,Buffet,1,0
3,Addhuri Udupi Bhojana,3.7/5,88,Banashankari,Quick Bites,"South Indian, North Indian",300,Buffet,0,0
4,Grand Village,3.8/5,166,Basavanagudi,Casual Dining,"North Indian, Rajasthani",600,Buffet,0,0
...,...,...,...,...,...,...,...,...,...,...
95,Vi Ra's Bar and Restaurant,3.3/5,62,Banashankari,Bar,"South Indian, North Indian, Chinese",800,Delivery,0,0
96,Kaggis,3.8/5,64,Banashankari,Quick Bites,"Fast Food, Bakery",250,Delivery,0,0
97,Ayda Persian Kitchen,3.7/5,39,Banashankari,Casual Dining,"North Indian, Iranian",950,Delivery,0,0
98,Chatar Patar,3.7/5,65,Banashankari,Quick Bites,"Fast Food, Street Food",300,Delivery,0,0
99,Polar Bear,3.8/5,71,Basavanagudi,Dessert Parlor,"Ice Cream, Desserts, Beverages, Sandwich",400,Delivery,1,0

In [249]:
null_values =df.isnull().mean().mul(100)
# null_values.sort()
print(null_values.sort_values())

name                            0.000000
votes                           0.000000
listed_in(type)                 0.000000
online_orderN                   0.000000
book_tableN                     0.000000
location                        0.040606
cuisines                        0.087012
rest_type                       0.438927
approx_cost(for two people)     0.669026
rate                           15.033741
dtype: float64

In [250]:
df.dtypes

name                             str
rate                             str
votes                          int64
location                         str
rest_type                        str
cuisines                         str
approx_cost(for two people)      str
listed_in(type)                  str
online_orderN                  int64
book_tableN                    int64
dtype: object

In [251]:
df.head(100)

,name,rate,votes,location,rest_type,cuisines,approx_cost(for two people),listed_in(type),online_orderN,book_tableN
0,Jalsa,4.1/5,775,Banashankari,Casual Dining,"North Indian, Mughlai, Chinese",800,Buffet,1,1
1,Spice Elephant,4.1/5,787,Banashankari,Casual Dining,"Chinese, North Indian, Thai",800,Buffet,1,0
2,San Churro Cafe,3.8/5,918,Banashankari,"Cafe, Casual Dining","Cafe, Mexican, Italian",800,Buffet,1,0
3,Addhuri Udupi Bhojana,3.7/5,88,Banashankari,Quick Bites,"South Indian, North Indian",300,Buffet,0,0
4,Grand Village,3.8/5,166,Basavanagudi,Casual Dining,"North Indian, Rajasthani",600,Buffet,0,0
...,...,...,...,...,...,...,...,...,...,...
95,Vi Ra's Bar and Restaurant,3.3/5,62,Banashankari,Bar,"South Indian, North Indian, Chinese",800,Delivery,0,0
96,Kaggis,3.8/5,64,Banashankari,Quick Bites,"Fast Food, Bakery",250,Delivery,0,0
97,Ayda Persian Kitchen,3.7/5,39,Banashankari,Casual Dining,"North Indian, Iranian",950,Delivery,0,0
98,Chatar Patar,3.7/5,65,Banashankari,Quick Bites,"Fast Food, Street Food",300,Delivery,0,0
99,Polar Bear,3.8/5,71,Basavanagudi,Dessert Parlor,"Ice Cream, Desserts, Beverages, Sandwich",400,Delivery,1,0

In [252]:
df['rate'] = df['rate'].str.replace('/5', '')  
df['rate'] = pd.to_numeric(df['rate'],errors='coerce')

df.head(10)

,name,rate,votes,location,rest_type,cuisines,approx_cost(for two people),listed_in(type),online_orderN,book_tableN
0,Jalsa,4.1,775,Banashankari,Casual Dining,"North Indian, Mughlai, Chinese",800,Buffet,1,1
1,Spice Elephant,4.1,787,Banashankari,Casual Dining,"Chinese, North Indian, Thai",800,Buffet,1,0
2,San Churro Cafe,3.8,918,Banashankari,"Cafe, Casual Dining","Cafe, Mexican, Italian",800,Buffet,1,0
3,Addhuri Udupi Bhojana,3.7,88,Banashankari,Quick Bites,"South Indian, North Indian",300,Buffet,0,0
4,Grand Village,3.8,166,Basavanagudi,Casual Dining,"North Indian, Rajasthani",600,Buffet,0,0
5,Timepass Dinner,3.8,286,Basavanagudi,Casual Dining,North Indian,600,Buffet,1,0
6,Rosewood International Hotel - Bar & Restaurant,3.6,8,Mysore Road,Casual Dining,"North Indian, South Indian, Andhra, Chinese",800,Buffet,0,0
7,Onesta,4.6,2556,Banashankari,"Casual Dining, Cafe","Pizza, Cafe, Italian",600,Cafes,1,1
8,Penthouse Cafe,4.0,324,Banashankari,Cafe,"Cafe, Italian, Continental",700,Cafes,1,0
9,Smacznego,4.2,504,Banashankari,Cafe,"Cafe, Mexican, Italian, Momos, Beverages",550,Cafes,1,0

In [253]:
g = df.groupby('approx_cost(for two people)')
g.groups.keys()

dict_keys(['1,000', '1,050', '1,100', '1,200', '1,250', '1,300', '1,350', '1,400', '1,450', '1,500', '1,600', '1,650', '1,700', '1,800', '1,900', '100', '120', '130', '140', '150', '160', '180', '190', '199', '2,000', '2,100', '2,200', '2,300', '2,400', '2,500', '2,600', '2,700', '2,800', '200', '230', '240', '250', '3,000', '3,200', '3,400', '3,500', '3,700', '300', '330', '350', '360', '4,000', '4,100', '4,500', '40', '400', '450', '469', '5,000', '50', '500', '550', '560', '6,000', '60', '600', '650', '70', '700', '750', '80', '800', '850', '900', '950'])

In [254]:
df['approx_cost(for two people)'] = df['approx_cost(for two people)'].str.replace(',','')
# df['approx_cost(for two people)'] = df['approx_cost(for two people)'].astype(int)
df['approx_cost(for two people)'] = pd.to_numeric(df['approx_cost(for two people)'],errors='coerce')

In [255]:
g = df.groupby('listed_in(type)')
g.groups.keys()

dict_keys(['Buffet', 'Cafes', 'Delivery', 'Desserts', 'Dine-out', 'Drinks & nightlife', 'Pubs and bars'])

In [256]:
df['Buffet'] = np.where(df['listed_in(type)']=='Buffet', 1, 0)
df['Cafes'] = np.where(df['listed_in(type)']=='Cafes', 1, 0)
df['Delivery'] = np.where(df['listed_in(type)']=='Delivery', 1, 0)
df['Desserts'] = np.where(df['listed_in(type)']=='Desserts', 1, 0)
df['Dine-out'] = np.where(df['listed_in(type)']=='Dine-out', 1, 0)
df['Drinks & nightlife'] = np.where(df['listed_in(type)']=='Drinks & nightlife', 1, 0)
df['Pubs and bars'] = np.where(df['listed_in(type)']=='Pubs and bars', 1, 0)

In [257]:
df.drop(columns=['listed_in(type)'],inplace=True)

In [258]:
df.dtypes

name                               str
rate                           float64
votes                            int64
location                           str
rest_type                          str
cuisines                           str
approx_cost(for two people)    float64
online_orderN                    int64
book_tableN                      int64
Buffet                           int64
Cafes                            int64
Delivery                         int64
Desserts                         int64
Dine-out                         int64
Drinks & nightlife               int64
Pubs and bars                    int64
dtype: object

In [259]:
df['location'] = df['location'].fillna('Unknown')
df['rest_type'] = df['rest_type'].fillna('Unknown')
df['cuisines']  = df['cuisines'].fillna('Unknown')
df['approx_cost(for two people)']  = df['approx_cost(for two people)'].fillna(df['approx_cost(for two people)'].median())

In [260]:
null_values =df.isnull().mean().mul(100)
# null_values.sort()
print(null_values.sort_values())

name                            0.000000
votes                           0.000000
location                        0.000000
rest_type                       0.000000
approx_cost(for two people)     0.000000
cuisines                        0.000000
online_orderN                   0.000000
book_tableN                     0.000000
Desserts                        0.000000
Buffet                          0.000000
Cafes                           0.000000
Delivery                        0.000000
Drinks & nightlife              0.000000
Dine-out                        0.000000
Pubs and bars                   0.000000
rate                           19.436549
dtype: float64

In [261]:
# Frequency encode location
location_freq = df['location'].value_counts(normalize=True)
df['location'] = df['location'].map(location_freq)

# Frequency encode rest_type
rest_type_freq = df['rest_type'].value_counts(normalize=True)
df['rest_type'] = df['rest_type'].map(rest_type_freq)

In [262]:
df.head()

,name,rate,votes,location,rest_type,cuisines,approx_cost(for two people),online_orderN,book_tableN,Buffet,Cafes,Delivery,Desserts,Dine-out,Drinks & nightlife,Pubs and bars
0,Jalsa,4.1,775,0.017518,0.199741,"North Indian, Mughlai, Chinese",800.0,1,1,1,0,0,0,0,0,0
1,Spice Elephant,4.1,787,0.017518,0.199741,"Chinese, North Indian, Thai",800.0,1,0,1,0,0,0,0,0,0
2,San Churro Cafe,3.8,918,0.017518,0.003345,"Cafe, Mexican, Italian",800.0,1,0,1,0,0,0,0,0,0
3,Addhuri Udupi Bhojana,3.7,88,0.017518,0.369936,"South Indian, North Indian",300.0,0,0,1,0,0,0,0,0,0
4,Grand Village,3.8,166,0.013226,0.199741,"North Indian, Rajasthani",600.0,0,0,1,0,0,0,0,0,0

In [263]:
df['cuisines_list'] = df['cuisines'].str.split(', ')
all_cuisines = df['cuisines_list'].explode()
cuisine_counts = Counter(all_cuisines)
top_25 = [cuisine for cuisine, count in cuisine_counts.most_common(25)]
print(top_25)

['North Indian', 'Chinese', 'South Indian', 'Fast Food', 'Biryani', 'Continental', 'Desserts', 'Cafe', 'Beverages', 'Italian', 'Bakery', 'Street Food', 'Pizza', 'Burger', 'Seafood', 'Ice Cream', 'Andhra', 'Mughlai', 'Rolls', 'American', 'Kerala', 'Asian', 'Momos', 'Finger Food', 'Juices']

In [264]:
def keep_top_cuisines(cuisine_list):
    return [c if c in top_25 else 'Other' for c in cuisine_list]

df['cuisines_list'] = df['cuisines_list'].apply(keep_top_cuisines)

In [265]:
from sklearn.preprocessing import MultiLabelBinarizer

mlb = MultiLabelBinarizer()
cuisine_encoded = mlb.fit_transform(df['cuisines_list'])

# convert to dataframe with proper column names
cuisine_df = pd.DataFrame(
    cuisine_encoded,
    columns=['cuisine_' + c for c in mlb.classes_],
    index=df.index
)

print(cuisine_df.shape)   # should be (41263, 26) — 25 cuisines + Other
print(cuisine_df.columns.tolist())

(51717, 26)
['cuisine_American', 'cuisine_Andhra', 'cuisine_Asian', 'cuisine_Bakery', 'cuisine_Beverages', 'cuisine_Biryani', 'cuisine_Burger', 'cuisine_Cafe', 'cuisine_Chinese', 'cuisine_Continental', 'cuisine_Desserts', 'cuisine_Fast Food', 'cuisine_Finger Food', 'cuisine_Ice Cream', 'cuisine_Italian', 'cuisine_Juices', 'cuisine_Kerala', 'cuisine_Momos', 'cuisine_Mughlai', 'cuisine_North Indian', 'cuisine_Other', 'cuisine_Pizza', 'cuisine_Rolls', 'cuisine_Seafood', 'cuisine_South Indian', 'cuisine_Street Food']

In [266]:
df = pd.concat([df, cuisine_df], axis=1)
df.drop(columns=['cuisines', 'cuisines_list'], inplace=True)

In [267]:
df.head()

,name,rate,votes,location,rest_type,approx_cost(for two people),online_orderN,book_tableN,Buffet,Cafes,...,cuisine_Kerala,cuisine_Momos,cuisine_Mughlai,cuisine_North Indian,cuisine_Other,cuisine_Pizza,cuisine_Rolls,cuisine_Seafood,cuisine_South Indian,cuisine_Street Food
0,Jalsa,4.1,775,0.017518,0.199741,800.0,1,1,1,0,...,0,0,1,1,0,0,0,0,0,0
1,Spice Elephant,4.1,787,0.017518,0.199741,800.0,1,0,1,0,...,0,0,0,1,1,0,0,0,0,0
2,San Churro Cafe,3.8,918,0.017518,0.003345,800.0,1,0,1,0,...,0,0,0,0,1,0,0,0,0,0
3,Addhuri Udupi Bhojana,3.7,88,0.017518,0.369936,300.0,0,0,1,0,...,0,0,0,1,0,0,0,0,1,0
4,Grand Village,3.8,166,0.013226,0.199741,600.0,0,0,1,0,...,0,0,0,1,1,0,0,0,0,0

In [268]:
df.dropna(subset=["rate"])
df.drop(columns= ['name'],inplace=True)

In [269]:
df.dtypes

rate                           float64
votes                            int64
location                       float64
rest_type                      float64
approx_cost(for two people)    float64
online_orderN                    int64
book_tableN                      int64
Buffet                           int64
Cafes                            int64
Delivery                         int64
Desserts                         int64
Dine-out                         int64
Drinks & nightlife               int64
Pubs and bars                    int64
cuisine_American                 int64
cuisine_Andhra                   int64
cuisine_Asian                    int64
cuisine_Bakery                   int64
cuisine_Beverages                int64
cuisine_Biryani                  int64
cuisine_Burger                   int64
cuisine_Cafe                     int64
cuisine_Chinese                  int64
cuisine_Continental              int64
cuisine_Desserts                 int64
cuisine_Fast Food                int64
cuisine_Finger Food              int64
cuisine_Ice Cream                int64
cuisine_Italian                  int64
cuisine_Juices                   int64
cuisine_Kerala                   int64
cuisine_Momos                    int64
cuisine_Mughlai                  int64
cuisine_North Indian             int64
cuisine_Other                    int64
cuisine_Pizza                    int64
cuisine_Rolls                    int64
cuisine_Seafood                  int64
cuisine_South Indian             int64
cuisine_Street Food              int64
dtype: object

In [270]:
df = df.replace(
    ['nan', 'NaN', 'NAN', 'none', 'None', 'NONE', 
     'null', 'Null', 'NULL', 'na', 'NA', 'N/A', 'Nan',
     '', ' ', '-', '--', '?'],
    np.nan
)

# Remove spaces from string columns
df = df.apply(lambda col: col.str.strip() if col.dtype == 'object' else col)

# Again convert empty strings after stripping
df = df.replace('', np.nan)

# Drop all rows that have even one missing value
df = df.dropna()

print(df.isnull().sum())
print(df.shape)

rate                           0
votes                          0
location                       0
rest_type                      0
approx_cost(for two people)    0
online_orderN                  0
book_tableN                    0
Buffet                         0
Cafes                          0
Delivery                       0
Desserts                       0
Dine-out                       0
Drinks & nightlife             0
Pubs and bars                  0
cuisine_American               0
cuisine_Andhra                 0
cuisine_Asian                  0
cuisine_Bakery                 0
cuisine_Beverages              0
cuisine_Biryani                0
cuisine_Burger                 0
cuisine_Cafe                   0
cuisine_Chinese                0
cuisine_Continental            0
cuisine_Desserts               0
cuisine_Fast Food              0
cuisine_Finger Food            0
cuisine_Ice Cream              0
cuisine_Italian                0
cuisine_Juices                 0
cuisine_Kerala                 0
cuisine_Momos                  0
cuisine_Mughlai                0
cuisine_North Indian           0
cuisine_Other                  0
cuisine_Pizza                  0
cuisine_Rolls                  0
cuisine_Seafood                0
cuisine_South Indian           0
cuisine_Street Food            0
dtype: int64
(41665, 40)

In [271]:
df.to_csv('final.csv', index=False)